version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant-mem0
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-mem0-data:/qdrant/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readiness"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  qdrant-mem0-data:
    name: qdrant-mem0-data
