@echo off
echo Stopping all Python processes...
taskkill /F /IM python.exe 2>nul
echo Waiting a moment for processes to terminate...
timeout /t 1 /nobreak > nul
echo Starting the application...
start python main.py
echo Restart complete!
